# -*- coding: utf-8 -*-
"""Dados de estações de carregamento de veículos elétricos globais

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MP49KSiVBvS8MnHnOuUqduHltz2Kg-iS
"""

import pandas as pd
import numpy as np

df = pd.read_csv('detailed_ev_charging_stations.csv')

df.dtypes

df.duplicated().sum()

df.isnull().sum()

"""**Qual é a média de custo por kWh das estações de carregamento?**"""

df['Cost (USD/kWh)'].mean()

"""**Quantas estações utilizam fontes de energia renovável?**"""

df['Renewable Energy Source'].value_counts()

"""Verificando a quantidade de estações que possuem fontes de energia renovável. **Conclusão:**
- 2566 estações possuem fontes de energia renovável
- 2434 que não possuem fontes de energia renovavel

**Qual é a média de avaliações (reviews) das estações?**
"""

df.head()
df['Reviews (Rating)'].mean().round()

"""Em resposta, temos a conclusão que a média das avaliações das estações são de **4.0**

**Qual é o total de vagas de estacionamento disponíveis em todas as estações?**
"""

df.head()
df['Parking Spots'].sum()

"""O Total de vagas de estacionamento disponível para o carregamento dos carros elétircos é de **27598** lugares

**Quantas estações possuem carregamento rápido (por exemplo, acima de 50 kW)?**
"""

df.head()
df[df['Charging Capacity (kW)'] > 50].shape[0]

"""A quantidade de carrgeadores capacitados com o carregamento rápido (acima de 50 kW)é de **2539** carregadores

**Qual é a média da capacidade de carregamento (kW) por tipo de conector?**
"""

df.head(2)
df.groupby('Connector Types')['Charging Capacity (kW)'].mean().round(2)

import matplotlib.pyplot as plt

mean_capacity_by_connector = df.groupby('Connector Types')['Charging Capacity (kW)'].mean().round(2)
mean_capacity_by_connector.plot(kind='bar', color='skyblue')
plt.title('Média de Capacidade de Carregamento por Tipo de Conector')
plt.xlabel('Tipo de Conector')
plt.ylabel('Média de Capacidade (kW)')
plt.xticks(rotation=90)
plt.show

"""**Existe correlação entre a capacidade de carregamento (kW) e o número médio de usuários por dia?**"""

df.head(2)
df[['Charging Capacity (kW)', 'Usage Stats (avg users/day)']].corr()

"""A correlação entre a capacidade de carregamento e o número médio de usuários por dia é extremamente baixa, ou seja, praticamente não a correlação

**Qual o custo médio por kWh para estações que utilizam energia renovável vs. não renovável?**
"""

df.head(2)
df.groupby('Renewable Energy Source')['Cost (USD/kWh)'].mean()

plt.figure(figsize=(8, 6))
mean_cost_energy_sourse =df.groupby('Renewable Energy Source')['Cost (USD/kWh)'].mean()
mean_cost_energy_sourse.plot(kind='barh', color=['skyblue', 'lightcoral'])
plt.title('Custo Médio por kWh para Estações Renováveis vs. Não Renováveis')
plt.xlabel('Tipo de Energia Renovável')
plt.ylabel('Custo Médio por kWh')
plt.xlim(left=mean_cost_energy_sourse.min() * 0.9)
plt.grid(axis='x', linestyle='--', alpha=0.7)
plt.show()

"""A diferença é muito pequena quando coolocado no gráfico, porém concluímos que o custo médio para as estações que utilizam a energia do tipo renovável é maior

**Quais são os 3 operadores de estação com maior número de pontos de carregamento?**
"""

df.groupby('Station Operator')['Parking Spots'].sum().sort_values(ascending=False).head(3)

most_station_infrastructure = df.groupby('Station Operator')['Parking Spots'].sum().sort_values(ascending=False).head(3)

colors = ['lightblue' if x < most_station_infrastructure.max() else 'royalblue' for x in most_station_infrastructure]

plt.figure(figsize=(8, 6))
bars = most_station_infrastructure.plot(kind='barh', color=colors, edgecolor='black')

plt.title('Os 3 Operadores de Estação com Maior Número de Postos de Carregamento')
plt.xlabel('Número de Postos de Carregamento')
plt.ylabel('Operador de Estação')
plt.xlim(left=most_station_infrastructure.min() * 0.9)
plt.grid(axis='x', linestyle='--', alpha=0.7)
plt.show()